language: cpp
before_install:
  - yes | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev qtchooser qtdeclarative5-dev
script: qtchooser -run-tool=qmake -qt=qt5 && make