language: cpp
before_install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev qtchooser
script: qtchooser -run-tool=qmake -qt=qt5 && make